version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8082:8080"
    volumes:
      - jenkins-data:/var/jenkins_home
    networks:
      - devops-network

  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data
    networks:
      - devops-network

  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    networks:
      - devops-network
    # environment:
    #   - SONARQUBE_ADMIN_LOGIN=admin
    #   - SONARQUBE_ADMIN_PASSWORD=admin
networks:
  devops-network:
    driver: bridge

volumes:
  jenkins-data:
  nexus-data:
